# Generated by Django 6.0.1 on 2026-02-01 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda_API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direccion', to='Agenda_API.contacto'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='no_int',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', to='Agenda_API.contacto'),
        ),
    ]
