# Generated by Django 6.0.1 on 2026-02-01 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda_API', '0002_alter_direccion_contacto_alter_direccion_no_int_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='contacto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='direccion', to='Agenda_API.contacto'),
        ),
    ]
